# Generated by Django 4.1.1 on 2022-10-22 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_todo', models.CharField(max_length=60)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField()),
                ('doneOrNot', models.BooleanField()),
            ],
        ),
    ]
