# Generated by Django 4.1.1 on 2022-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_alter_boss_doneornot_alter_boss_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='boss',
            name='doneOrNot',
        ),
        migrations.RemoveField(
            model_name='boss',
            name='priority',
        ),
    ]
