# Generated by Django 4.1.1 on 2022-11-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_remove_boss_date_posted_remove_boss_doneornot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
